version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: stockradar
      POSTGRES_PASSWORD: stockradar
      POSTGRES_DB: stockradar
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
